
import { Drill, DrillLevel } from './types';

export const DRILLS: Drill[] = [
  {
    id: 'master-1',
    title: 'The AI Revolution in Creative Writing',
    level: DrillLevel.BEGINNER,
    type: 'Essay',
    wordCount: 880,
    description: 'A mechanics nightmare. Fix pervasive typos (teh, recieve), inconsistent capitalization, and basic punctuation errors that undermine the author’s credibility.',
    originalText: `Teh world of literature is currently undergoing a massive shift, and its all thanks to the rise of artificial intelligence. many critics argue that AI will eventually replace human authors entirely, but others believe that it is simply another tool in teh writers toolbox. before we can understand where we are going, we must look at where we have been. in the early days of computing, people used simple word processors to write there stories. but today, we have sophisticated algorithms that can generate entire paragraphs of text in a matter of seconds. it is truely a remarkable time to be alive, although many people are rightfully concerned about the future of creativity.

One of the biggest problems with AI writing is that it often lacks the "human touch" that makes a story resonate with readers. machines can follow rules and patterns, but they dont have feelings or experiences to draw from. for example, an AI might be able to describe a sunset, but it doesnt know what it feels like to sit on a beach and watch the sky turn orange and pink with someone you love. This lack of emotional depth is why many people still prefer books written by actual humans. however, the technology is improving every day, and some people say that we wont be able to tell teh difference between human and AI writing in just a few years. i personaly find this hard to believe, but i suppose anything is possible in this digital age.

Furthermore, there is the issue of intellectual property and copyright law. if a machine writes a book, who owns the rights to it? is it the person who programmed the AI, or is it the AI itself? this is a question that lawyers and legislators are currently grappling with. there have already been several high-profile cases where artists have sued AI companies for using there work to train there algorithms. its a mess, and it doesnt look like it will be resolved anytime soon. we need clear guidelines and regulations to protect the rights of human creators. if we dont act now, we risk losing the very thing that makes us human.

In addition to the legal and ethical issues, there is also the problem of misinformation. AI can be used to generate realistic-looking news articles and social media posts that are completely false. this is a major threat to democracy and public trust. we saw this happen during teh last election cycle, and its likely to get worse in the future. we need to educate the public on how to spot AI-generated content and encourage them to verify information from multiple sources. its a daunting task, but we have no choice if we want to maintain an informed citizenry. 

Another thing to consider is the impact on education. many students are now using AI to write there essays and complete there assignments. this is a form of cheating that is very difficult for teachers to detect. it also prevents students from developing there own critical thinking and writing skills. if we want the next generation to be able to communicate effectively, we must find ways to integrate technology into the classroom without allowing it to replace the learning process. maybe we should go back to writing essays by hand in class? its a radical idea, but it might be the only way to ensure that students are actually doing the work themselves.

In conclusion, teh rise of AI in creative writing is a complex issue with no easy answers. it offers many benefits, such as increased productivity and new forms of storytelling, but it also poses significant risks to creativity, ethics, and truth. we must proceed with caution and ensure that we are using these tools to enhance human potential, rather than replace it. teh future of literature depends on our ability to strike a balance between innovation and tradition. we must never forget that behind every great book is a human heart, and no machine can ever truly replace that. if we keep this in mind, we can navigate teh challenges of teh digital revolution and build a world where both humans and machines can coexist and thrive in teh pursuit of artistic excellence. we must be vigilant and proactive in our approach, always questioning teh impact of teh technology we create and ensuring that it serves teh greater good of humanity. the journey ahead will be long and difficult, but it is one that we must undertake together if we want to preserve teh beauty and power of the written word for generations to recieve.`
  },
  {
    id: 'master-2',
    title: 'Sustainability: A Corporate Perspective',
    level: DrillLevel.INTERMEDIATE,
    type: 'Essay',
    wordCount: 950,
    description: 'Wordiness and Passive Voice. The author uses 20 words where 5 would do. Strip away the corporate bloat and passive constructions to find the actual message.',
    originalText: `It is an indisputable fact that is widely recognized by a significant majority of stakeholders within the contemporary global business environment that the implementation of sustainable practices is of paramount importance for the long-term viability of corporate entities. In the current landscape, it has been observed by many observers that companies that fail to adopt environmentally friendly policies are often subjected to a high degree of scrutiny by both consumers and regulatory bodies alike. This scrutiny is often driven by a growing awareness of the impact of human activities on the natural environment, which is something that can no longer be ignored by those who are in positions of leadership within the private sector.

It is frequently stated by many industry experts that the integration of sustainability into the core business strategy is a process that requires a multi-faceted approach. This approach must involve the participation of all employees across all levels of the organization, from the entry-level staff to the members of the executive board. It is felt by many that without a culture of sustainability, any efforts to reduce the carbon footprint of the company will be ultimately unsuccessful. Therefore, it is necessary for management to provide the necessary resources and training to ensure that everyone is aligned with the goals of the organization in this regard.

Furthermore, the reporting of sustainability metrics is something that is being increasingly demanded by investors who are looking for transparency in the way that companies manage their environmental and social risks. It has been found that companies that are able to provide clear and concise data on their sustainability performance are often rewarded with a higher valuation in the capital markets. This is because investors view these companies as being better managed and more resilient to the challenges of the future. However, it should be noted that there is currently a lack of standardization in the way that these metrics are reported, which makes it difficult for investors to compare the performance of different companies in a meaningful way.

In addition to the environmental aspects of sustainability, there is also a social dimension that must be taken into consideration by those who are responsible for the management of corporate entities. This involves the fair treatment of workers, the promotion of diversity and inclusion, and the engagement with local communities. It is generally believed that companies that are seen as being socially responsible are better able to attract and retain top talent, which is a key driver of competitive advantage in the modern economy. This is especially true for the younger generations of workers, such as Millennials and Gen Z, who are often more motivated by a sense of purpose than by financial rewards alone.

Another area where sustainability can have a significant impact is in the supply chain. It is often the case that the environmental and social impacts of a company's operations are located deep within its supply chain, rather than within its own facilities. Therefore, it is imperative for companies to work closely with their suppliers to ensure that they are also adhering to high standards of sustainability. This can involve the conducting of audits, the setting of performance targets, and the provision of support to help suppliers improve their practices. It is a complex and challenging task, but it is one that must be undertaken if a company is to be truly sustainable in its operations.

In conclusion, it can be said that the journey towards sustainability is one that is fraught with challenges and opportunities for corporate entities. It requires a fundamental shift in the way that business is conducted, and a commitment to long-term value creation over short-term profits. While there is still a long way to go, it is encouraging to see that many companies are already making significant progress in this area. By working together, we can build a more sustainable future for ourselves and for the generations that will follow in our footsteps. The implementation of these strategies is being actively pursued by many forward-thinking organizations, yet it remains to be seen if the pace of change will be sufficient to address the urgent challenges of climate change and social inequality that are currently facing our global society. The cost of inaction is too high for us to contemplate, and therefore it is necessary for us to act with a sense of urgency and purpose in the pursuit of a more sustainable world for all of its inhabitants.`
  },
  {
    id: 'master-3',
    title: 'The Future of Renewable Energy',
    level: DrillLevel.INTERMEDIATE,
    type: 'Journalism',
    wordCount: 1020,
    description: 'Complexity and Reader Fatigue. Many sentences are over 50 words long with nested clauses. Break them down for a general audience.',
    originalText: `The global transition toward a renewable energy infrastructure, which is a process necessitated by the increasingly dire warnings issued by the Intergovernmental Panel on Climate Change regarding the anthropogenic drivers of atmospheric warming and the subsequent destabilization of long-term meteorological patterns, represents perhaps the most significant engineering and logistical challenge that the human species has ever collectively attempted to undertake since the dawn of the Industrial Revolution. While the technological feasibility of solar photovoltaic arrays and wind turbine farms has been demonstrated through decades of research and development, the primary obstacle that remains is the inherent intermittency of these energy sources, which, unlike the baseload power provided by coal-fired or nuclear thermal plants, do not produce a constant stream of electricity regardless of the time of day or the prevailing weather conditions in a given geographic region.

To address this fundamental limitation, scientists and engineers are currently investigating a wide variety of energy storage solutions, ranging from large-scale lithium-ion battery installations that can provide rapid response during peak demand periods to more experimental concepts such as pumped hydroelectric storage and compressed air energy systems, which, although they require specific geological features to be viable, offer the potential for much larger capacities and longer duration storage than current chemical battery technologies are capable of providing at a cost-effective price point. 

Furthermore, the modernization of the electrical grid, often referred to as the "smart grid" initiative, is another critical component of the transition, as it involves the deployment of advanced sensors and automated control systems that allow for a two-way flow of both electricity and information between the utility provider and the end consumer, thereby enabling a more efficient allocation of resources and allowing for the seamless integration of distributed energy resources, such as rooftop solar panels and electric vehicle batteries, into the broader network. 

However, the political and economic hurdles associated with such a massive overhaul of the status quo are immense, as the fossil fuel industry, which has enjoyed a position of dominance in the global economy for over a century and possesses significant lobbying power in many national capitals, has a vested interest in slowing the pace of the transition in order to protect its existing assets and ensure that the trillions of dollars of infrastructure that it has already built do not become "stranded" before they have reached the end of their useful lives. 

In addition to the resistance from entrenched interests, there is also the issue of "energy poverty" in the developing world, where billions of people still lack access to basic electricity services and for whom the immediate priority is the acquisition of cheap and reliable power, which, in many cases, still means the construction of new coal plants, despite the long-term environmental consequences that such a path entails for the planet as a whole. 

Therefore, it is essential that the international community develops a coordinated strategy for financing and technology transfer that allows these nations to "leapfrog" the carbon-intensive stage of development and move directly to a renewable-based economy, a goal that was central to the discussions at the most recent United Nations Climate Change Conference, but which has yet to see the level of financial commitment from the world's wealthiest nations that is required to make it a reality. 

In conclusion, the path toward a sustainable energy future is one that is lined with both technical and political minefields, requiring a level of international cooperation and shared sacrifice that is rarely seen in the history of human geopolitics, yet the alternative, which is a world of increasingly frequent and severe natural disasters, mass migrations, and resource-driven conflicts, is so catastrophic that we have no choice but to persevere in our efforts to build a cleaner and more resilient world for ourselves and for the future generations who will inherit the consequences of the choices we make today. The complexity of the task at hand cannot be overstated, yet it is through the rigorous application of scientific principles and the collective will of a global community that we will find the solutions to these seemingly insurmountable problems, ensuring that the light of human civilization continues to shine brightly in the centuries to come.`
  },
  {
    id: 'master-4',
    title: 'Investigative: The Dark Side of Space Exploration',
    level: DrillLevel.ADVANCED,
    type: 'Journalism',
    wordCount: 1150,
    description: 'Structural and Logical Sequence issues. The narrative is jumbled. The lead is buried, and the evidence follows the conclusion. Reorder the flow.',
    originalText: `In conclusion, we must regulate the private space industry before it is too late. The stars are a common heritage of humanity, and they should not be sold to the highest bidder. But first, let’s look at the statistics of space debris. There are currently over 30,000 pieces of trackable "space junk" orbiting the Earth at speeds of up to 17,500 miles per hour. Even a small piece of metal can cause catastrophic damage to a multimillion-dollar satellite or the International Space Station. This is a tragedy waiting to happen.

The real story, however, began three years ago in a small laboratory in Texas. A group of whistleblowers from a prominent aerospace firm contacted this reporter with evidence of massive environmental violations at their launch site. They claimed that the company was dumping toxic fuel directly into the local groundwater, leading to a spike in rare cancers in the surrounding community. "They told us it was safe," said one former employee who requested anonymity for fear of retaliation. "But we saw the dead fish in the river every morning."

We should also consider the ethical implications of space mining. Companies like SpaceX and Blue Origin are already planning missions to asteroids that are rich in precious metals like platinum and gold. This could create the world's first trillionaires, further increasing the gap between the rich and the poor on Earth. Is this the kind of future we want to build? A future where the resources of the solar system are hoarded by a handful of billionaires while billions of people back home struggle to find clean water and food?

Wait, I forgot to mention the legal side of things. The Outer Space Treaty of 1967 states that no nation can claim sovereignty over any celestial body. But the treaty is silent on the issue of private property. This has created a "Wild West" atmosphere where companies are racing to stake their claims before any international regulations are put in place. It's a gold rush in the sky, and there are no sheriffs to keep the peace.

Back to the Texas launch site. We conducted our own soil tests and found levels of perchlorate that were ten times the legal limit. When we confronted the CEO of the company, he dismissed our findings as "junk science" and threatened to sue our publication. "We are pioneering the future of humanity," he said in a heated email. "A few dead fish are a small price to pay for the survival of our species." This is the arrogance of the new space race.

The carbon footprint of a single rocket launch is equivalent to that of a transatlantic flight, yet there are hundreds of launches every year. As the industry grows, so too will its impact on our atmosphere. Some scientists worry that the soot released by rockets could contribute to global warming in ways that we don't yet fully understand. Yet, because these launches happen in the upper atmosphere, they are often excluded from international climate agreements.

If we don't act now, the orbital environment will become so crowded and dangerous that it will be impossible for us to leave the planet at all. This is known as the "Kessler Syndrome," a theoretical scenario where the density of objects in low Earth orbit is high enough that collisions between objects could cause a cascade in which each collision generates space debris that increases the likelihood of further collisions. We are on the verge of locking ourselves in a cage of our own making.

The investigation continues, but one thing is clear: the private space industry is operating in a vacuum of accountability. From the toxic groundwater in Texas to the legal void of the asteroid belt, the costs of our cosmic ambitions are being externalized onto the most vulnerable members of our society and the environment. It is time for a global conversation about who owns the sky and how we intend to protect it for the generations to come. The thread of human history is being woven into the stars, but if we are not careful, it will become a noose. The greed and short-sightedness that have devastated our home planet are now being exported to the final frontier, and we must ask ourselves if we are truly ready to be a multi-planetary species if we cannot even manage the one we have.`
  },
  {
    id: 'master-5',
    title: 'The Ethics of Genetic Engineering',
    level: DrillLevel.ADVANCED,
    type: 'Essay',
    wordCount: 1100,
    description: 'Tone Inconsistency. The writing shifts from high-level academic discourse to "unprofessional slang" and back. Harmonize the voice into a serious, reflective essay.',
    originalText: `The ontological status of the human genome has long been a subject of intense philosophical inquiry within the field of bioethics. We are basically talking about whether we should be playing god with our DNA, and honestly, some of this stuff is just totally bugging. The advent of CRISPR-Cas9 technology has provided humanity with a level of precision in genetic manipulation that was previously the stuff of science fiction. It's like we found the cheat codes for the human body, but we don't know if we're gonna get banned from the server for using them.

Proponents of germline editing argue that we have a moral obligation to eliminate hereditary diseases such as cystic fibrosis and Huntington's disease. From a utilitarian perspective, the reduction of human suffering is a primary ethical imperative that justifies the risks associated with the technology. Like, if you could make sure your kid doesn't have a terrible disease, you'd be a total hater not to do it, right? It's a no-brainer for most parents who just want their kids to be healthy and have a good vibe in life.

However, the specter of "designer babies" looms large over the discussion, raising concerns about a new form of eugenics that could exacerbate existing social inequalities. If the wealthy are able to purchase genetic enhancements for their children—such as increased intelligence, athletic ability, or aesthetic appeal—we risk creating a biological caste system that would be impossible to overcome through traditional social means. This would be a major L for society. We're talking about a literal master race of super-smart, super-hot rich people while everyone else is left in the dust. It's giving very much dystopian nightmare energy, and I am not here for it.

Furthermore, we must consider the unintended consequences of messing with the gene pool. Evolution has spent millions of years fine-tuning our DNA, and we think we can just walk in and start changing things after a few years of research? That's some major hubris right there. Genetic traits are often linked in ways that we don't fully understand, and fixing one problem might create three more that are even worse. It's like trying to fix a bug in a video game and accidentally deleting the whole map. We need to be super careful or we might accidentally delete the human race.

The concept of "human nature" is also at stake in these debates. If we begin to view ourselves as mere biological machines that can be optimized for performance, what happens to our sense of agency and moral responsibility? Are we still human if our every trait was selected for us by our parents and a team of scientists? This is some deep, big-brain stuff that requires us to really think about what it means to be alive. We can't just yolo our way into a post-human future without a serious conversation about the soul and the spirit.

In conclusion, the ethics of genetic engineering represent a fundamental challenge to our understanding of ourselves and our place in the universe. We need clear regulations and a global consensus before we proceed any further. We can't let the tech bros and the greedy corporations decide the future of our species. It's too important to leave to the market. We need a movement that is grounded in wisdom, compassion, and a deep respect for the mystery of life. If we can do that, we might be able to use this technology for good. But if we fail, we're basically cooked. The stakes are literally as high as they can get, and we only have one shot at getting this right. We must transition from a posture of dominance over nature to one of stewardship and humility, recognizing that our power to change the world must be balanced by our wisdom to know when to leave it alone. The future of the human genome is in our hands, and we must treat it with the reverence it deserves, ensuring that the light of our humanity continues to shine brightly in an increasingly engineered world.`
  }
];
